// GeneralsX @feature Codex 14/09/2026 In-game guide follows physical hand
// roles and XR language, without depending on retail language assets.
#pragma once
#include "XrStrings.h"
constexpr int kXrControllerHelpPages=4;
inline std::string xrControllerHelp(int page,bool leftHanded) {
	static const XrTranslation pages[]={
	 {"SPIELEN UND AUSWÄHLEN\nZeigehand: {point}. Andere Hand: {support}.\nTrigger = vordere Taste; Grip = seitliche Grifftaste.\n\n{point} Trigger kurz: Einheit wählen / Kontextbefehl. Mit Auswahl: Boden = bewegen, Feind = angreifen; eigene Ziele ggf. reparieren / einsteigen.\n\n{point} Trigger halten + Laser ziehen: Auswahlrahmen. Loslassen wählt aus. {support} Grip beim Drücken: Auswahl ergänzen / einzelne Einheit abwählen.\n\n{support} Stick: Karte verschieben.\n{point} Stick links/rechts: Karte drehen; hoch/runter: hinein-/herauszoomen.\n\n{point} Grip: Zielmodus abbrechen, sonst Auswahl aufheben. {orders}: Befehle ein/aus.\n{back} oder System-Menütaste: Spielmenü.\n\nUI → Ansicht: Linkshändigkeit und Sprache.",
	  "PLAY AND SELECT\nPointing hand: {point}. Other hand: {support}.\nTrigger = front button; Grip = side squeeze button.\n\nShort {point} trigger press: select / context order. With selection: ground = move, enemy = attack; friendly targets may mean repair / enter.\n\nHold {point} trigger + drag laser: selection box. Release to select. Hold {support} Grip at press: add selection / remove a single unit.\n\n{support} stick: pan map.\n{point} stick left/right: rotate map; up/down: zoom in/out.\n\n{point} Grip: cancel targeting, otherwise deselect. {orders}: toggle commands.\n{back} or system menu button: game menu.\n\nUI → View: handedness and language."},
	 {"GEBÄUDE PLATZIEREN UND DREHEN\n1. Bauarbeiter wählen und im Baufenster ein Gebäude auswählen.\n2. Mit dem Laser auf den gewünschten Bauplatz zeigen.\n3. {support} Grip halten + {point} Stick links/rechts: Vorschau drehen (stufenlos, bis 90°/s).\n4. Grip und Stick loslassen. Die Ausrichtung bleibt erhalten.\n5. {point} Trigger kurz drücken: platzieren.\n\n{point} Grip: Bauplatzierung abbrechen.\n\nWährend des Drehens sind Kartendrehung, Zoom und Verschieben gesperrt. Nach dem Grip auch den Stick zentrieren. Während des Platzierungsklicks bleibt der Winkel fest.\n\nDie Originalregeln prüfen Bauplatz, Geld und Hindernisse. Rotieren macht einen gesperrten Bauplatz nicht gültig. Nur vor dem Bau; keine Drehung fertiger Gebäude. Linienbau ist von dieser Drehhilfe ausgenommen.",
	  "PLACE AND ROTATE BUILDINGS\n1. Select a worker and choose a building in the build window.\n2. Aim the laser at the intended construction site.\n3. Hold {support} Grip + move {point} stick left/right: rotate preview (continuous, up to 90°/s).\n4. Release Grip and center the stick. Orientation is retained.\n5. Short {point} trigger press: place.\n\n{point} Grip: cancel construction placement.\n\nMap rotation, zoom and pan are blocked while rotating. Center the stick after releasing Grip. The angle stays fixed during the placement click.\n\nOriginal rules check the site, money and obstacles. Rotation does not make a blocked site valid. Before construction only; finished buildings cannot be rotated. Line construction is excluded from this rotation aid."},
	 {"FENSTER UND SPIELBRETT\nUI → Fenster: Tisch oder Baufenster wählen. Orange + Häkchen markieren das Bearbeitungsziel; dasselbe Objekt hat einen orangenen Rahmen. Türkis zeigt nur den Laser-Hover.\n\nDie Schaltflächen ändern Größe, Abstand, Höhe und Neigung direkt. Mehr Karte ändert den Kartenausschnitt, nicht die Tischgröße.\n\nGreifen / Anordnen:\nEin Grip: ausgewähltes Objekt bewegen und neigen. Beide Grips: gleichmäßig skalieren.\nOhne Grip: {point} Stick hoch/runter = Größe; {support} Stick hoch/runter = Abstand entlang des Lasers.\n\n{point} Stick drücken: Tisch / Baufenster wechseln.\n{level}: waagerecht/aufrecht ausrichten bzw. freies Neigen.\n{reset}: gewähltes Objekt vor dir zurücksetzen.\nFertig, {orders} oder {back}: Bearbeitung beenden. Danach Tasten loslassen, Sticks zentrieren.\n\nSpielplatz einrichten (auch im Hauptmenü): freier Tisch, reale Fläche oder manuelle Höhe. Bei realen Flächen werden Raumdaten geladen; Tische/Boden wählen. Türkis = erkannte Fläche, Orange = gültiges Brett, Rot = zu groß. {point} Stick: Größe/Drehung; Trigger bestätigt, Grip zurück. Manuell: Controllerhöhe mit Trigger merken, danach zielen und erneut bestätigen. Keine Bindung über Neustarts.\n\nBau-Hover zeigt Preise und Voraussetzungen; lange Texte wechseln alle 10 Sekunden die Seite.",
	  "WINDOWS AND TABLE\nUI → Windows: select table or build window. Orange + check mark identify the editing target; the same object has an orange outline. Cyan only indicates laser hover.\n\nButtons directly change size, distance, height and tilt. More map changes map coverage, not physical table size.\n\nGrab / arrange:\nOne Grip: move and tilt the selected object. Both Grips: uniform scaling.\nWithout Grip: {point} stick up/down = size; {support} stick up/down = distance along the laser.\n\nPress {point} stick: switch table / build window.\n{level}: level/upright alignment or free tilt.\n{reset}: reset selected object in front of you.\nDone, {orders} or {back}: finish editing. Then release buttons and center sticks.\n\nSet up play space (also in the main menu): free board, real surface or manual height. Choose Tables/Floor after room data loads. Cyan = surface, orange = valid board, red = too large. {point} stick: size/rotation; trigger confirms, Grip goes back. Manual: record controller height with trigger, then aim and confirm again. No binding across restarts.\n\nBuild hover shows costs and requirements; long text advances every 10 seconds."},
	 {"BEFEHLE, GRUPPEN UND WEITERE KÜRZEL\nEinheiten auswählen → Bewegen / Angriffsmarsch / Bewachen → Ziel auf dem Tisch anklicken. STOPP und Auseinanderlaufen wirken sofort. Weitere Details: Befehle → Hilfe.\n\nGruppe anlegen: Einheiten markieren → Speichern → Zahl. Zahl allein ruft eine gespeicherte Gruppe auf.\nGruppe erweitern: neue Einheiten markieren → Zur Auswahl → Zahl → Speichern → dieselbe Zahl.\nWegpunkte an: mehrere Bewegungsziele anklicken; danach wieder ausschalten.\n\nIm Spiel, außerhalb der Bau-Drehhilfe:\n{point} Stick drücken: Kameraperspektive wechseln.\n{support} Trigger + {point} Stick hoch/runter: Kameraneigung (nicht die physische Tischneigung).\n{support} Trigger + {point} Stick drücken: Kamerafavorit speichern.\n{support} Trigger + {reset}: Kamerafavorit laden.\n{reset} allein: Brett und Fenster gemeinsam vor dir zentrieren. Einzelne Fenster nur unter UI → Fenster anordnen.\n\nVideos: Trigger oder {back} zum Überspringen, sofern vorgesehen. Bei Trackingverlust erfolgt kein Auftrag.",
	  "ORDERS, GROUPS AND EXTRA SHORTCUTS\nSelect units → Move / Attack move / Guard → click target on table. STOP and Scatter act immediately. More detail: Commands → Help.\n\nCreate group: select units → Save selection → number. Number alone recalls a stored group.\nExtend group: select new units → Add to selection → number → Save selection → same number.\nWaypoints on: click several movement destinations; turn it off afterward.\n\nIn play, outside building rotation:\nPress {point} stick: cycle camera preset.\n{support} trigger + {point} stick up/down: camera pitch (not physical table tilt).\n{support} trigger + press {point} stick: save camera favorite.\n{support} trigger + {reset}: load camera favorite.\n{reset} alone: recenter the board and windows together in front of you. Arrange individual windows under UI → Windows.\n\nVideos: trigger or {back} to skip where supported. Tracking loss never issues an order."}
	};
	const auto &entry=pages[page>=0 && page<kXrControllerHelpPages ? page:0];
	std::string text=g_xrLanguage==XrLanguage::German ? entry.de:entry.en;
	const char *keys[]={"{point}","{support}","{orders}","{back}","{reset}","{level}"};
	const char *values[]={xrTr(leftHanded ? "Links":"Rechts"),xrTr(leftHanded ? "Rechts":"Links"),
		leftHanded ? "X":"A",leftHanded ? "Y":"B",leftHanded ? "A":"X",leftHanded ? "B":"Y"};
	for(int i=0;i<6;++i)for(size_t pos=0;(pos=text.find(keys[i],pos))!=std::string::npos;) {
		text.replace(pos,std::strlen(keys[i]),values[i]);pos+=std::strlen(values[i]);
	}
	return text;
}
