// GeneralsX @feature Codex 14/09/2026 XR gettext-style catalog. Keep game
// asset text separate: it is resolved by the native string-table loader.
#pragma once
#include <string>
#include <cstring>
enum class XrLanguage {German,English};
inline XrLanguage g_xrLanguage=XrLanguage::German; // XR thread only
struct XrTranslation {const char *de,*en;};
inline constexpr XrTranslation kXrTranslations[]={
	// GeneralsX @feature Codex 17/09/2026 P25 bilingual observer controls.
	{"Bodenansicht","Ground view"},
	{"Bodenansicht · Ort wählen","Ground view · choose location"},
	{"Nur Offline-Gefecht: Bodenansicht wählen, dann sichtbaren freien Boden anklicken. B/Y kehrt zurück.",
	 "Offline Skirmish only: choose Ground view, then click visible open ground. B/Y returns."},
	{"B: Zurück zum Tisch","B: Return to table"},
	{"Y: Zurück zum Tisch","Y: Return to table"},
	{"Sichtbaren freien Boden mit Trigger wählen. B/Y bricht ab.","Choose visible open ground with the trigger. B/Y cancels."},
	{"Hier kein sicherer, sichtbarer Boden. Anderen Ort wählen; B/Y bricht ab.",
	 "No safe visible ground here. Choose another spot; B/Y cancels."},
	{"Spiel: Tisch; Bodenansicht optional","Game: table; Ground view optional"},
 {"Bearbeitung: %s · %.2f m · Karte %.1fx · P19.1","Editing: %s · %.2f m · Map %.1fx · P19.1"},
 // GeneralsX @feature Codex 14/09/2026 P19.1 optional placement wizard.
 {"Spielplatz einrichten · P19.1","Set up play space · P19.1"},
 {"Spielplatz einrichten","Set up play space"},
 {"Während Video oder Laden nicht verfügbar","Unavailable during movies or loading"},
 {"Kein Tisch gefunden; Raum erfassen oder Höhe manuell setzen","No table found; capture room or set height manually"},
 {"Kein Boden gefunden; Raum erfassen oder Höhe manuell setzen","No floor found; capture room or set height manually"},
 {"Freier Tisch aktiv; reale Fläche ist optional","Free-standing board active; real surfaces are optional"},
 {"1 / 3 · Platzierungsart wählen","1 / 3 · Choose placement"},
 {"Raumbezug verloren. Bitte neu platzieren oder freien Tisch wählen.","Room reference lost. Place again or choose a free-standing board."},
 {"Ohne Raumscan spielbar. Reale Flächen sind optional; Einrichtung auch vor einer Partie möglich.","No room scan required. Real surfaces are optional; setup also works before a match."},
 {"Freien Tisch verwenden","Use free-standing board"},
 {"Reale Fläche auswählen","Choose real surface"},
 {"Höhe manuell festlegen","Set height manually"},
 {"2 / 3 · Fläche auswählen","2 / 3 · Choose surface"},
 {"Tische und Boden werden in der Vorschau umrandet. Danach Größe und Ausrichtung einstellen.","Tables and floor are outlined in preview. Then adjust size and orientation."},
 {"Raumdaten neu laden","Reload room data"},
 {"3 / 3 · Bereit","3 / 3 · Ready"},
 {"Position gilt für diese Sitzung. Nach Neustart keine automatische Bindung an reale Möbel.","Placement lasts for this session. After restart, no automatic binding to real furniture."},
 {"Neu platzieren","Place again"},
 {"Controller auf gewünschte Flächenhöhe halten; Trigger merkt die Höhe. Grip: zurück.","Hold the controller at the desired surface height; trigger records height. Grip: back."},
 {"Zeigestick: hoch/runter Größe, links/rechts drehen. Trigger: bestätigen. Grip: zurück.","Pointing-hand stick: up/down size, left/right rotate. Trigger: confirm. Grip: back."},
 {"3 / 3 · Vorschau","3 / 3 · Preview"},
 {"Zurück","Back"},
 {"Keine passende Fläche; Typ wechseln oder Raum erfassen","No matching surface; switch type or capture room"},
 {"Auf Fläche stellen","Place on surface"},
 {"Raumdaten laden","Load room data"},
 {"Raum neu erfassen","Capture room"},
 {"Tische","Tables"},
 {"Boden","Floor"},
 {"✓ Tische","✓ Tables"},
 {"✓ Boden","✓ Floor"},
 {"Anpassen: AN","Fit to surface: ON"},
 {"Anpassen: AUS","Fit to surface: OFF"},
 {"Vorschau starten","Start preview"},
 {"Trigger: bestätigen","Trigger: confirm"},
 {"Grip: abbrechen","Grip: cancel"},
 {"Keine Dauerbindung","No persistent anchor"},
 {"Manuell bleibt möglich","Manual layout still works"},
 {"Bearbeitung: %s · %.2f m · Karte %.1fx · P19","Editing: %s · %.2f m · Map %.1fx · P19"},
 {"Raumdaten noch nicht geladen","Room data not loaded yet"},
 {"Raumflächen nicht unterstützt","Room surfaces not supported"},
 {"Raumdaten werden geladen","Loading room data"},
 {"Raumabfrage fehlgeschlagen","Room query failed"},
 {"Raumaufnahme nicht verfügbar","Room capture unavailable"},
 {"Raumaufnahme im System abschließen","Complete room capture in the system"},
 {"Raumaufnahme fehlgeschlagen","Room capture failed"},
 {"Keine Tische oder Böden gefunden","No tables or floors found"},
 {"Raumdaten bereit","Room data ready"},
 {"Raumaufnahme fertig; Daten neu laden","Capture complete; reload room data"},
 {"Raumaufnahme abgebrochen","Room capture cancelled"},
 {"Vorschau: Trigger bestätigen · Grip abbrechen","Preview: trigger confirms · grip cancels"},
 {"Zu wenig Platz: mittig zielen oder Anpassen aktivieren","Too small: aim at center or enable Fit"},
 {"Auf die gewählte Fläche zeigen · Grip abbrechen","Point at the chosen surface · grip cancels"},
 {"Flächen noch nicht lokalisiert · Grip abbrechen","Surfaces not located yet · grip cancels"},
 {"Raumfreigabe im System bestätigen","Approve room permission in the system"},
 {"Keine Raumfreigabe; manuelles Anordnen bleibt verfügbar","No room permission; manual layout still works"},
 {"Zuerst eine Partie im Tabletop öffnen","First open a match in tabletop"},
 {"Zuerst Raumdaten laden","Load room data first"},
 {"Platzierung unterbrochen; Vorschau neu starten","Placement interrupted; restart preview"},
 {"Platzierung abgebrochen","Placement cancelled"},
 {"Auf Fläche platziert; frei weiter anpassbar","Placed on surface; still freely adjustable"},
 {"Fläche zu weit entfernt","Surface is too far away"},
 {"Links","Left"},{"Rechts","Right"},
 {"Controller-Anleitung","Controller guide"},{"Zurück zu Fenstern","Back to windows"},
 {"Bearbeitung: %s · %.2f m · Karte %.1fx · P18.1","Editing: %s · %.2f m · Map %.1fx · P18.1"},
 {"Gebäude drehen","Rotate building"},
 {"Winkel %d° · Linker Grip + rechter Stick ↔ drehen. Rechter Trigger: bauen; rechter Grip: abbrechen.","Angle %d° · Left Grip + right stick ↔ rotate. Right trigger: build; right Grip: cancel."},
 {"Winkel %d° · Rechter Grip + linker Stick ↔ drehen. Linker Trigger: bauen; linker Grip: abbrechen.","Angle %d° · Right Grip + left stick ↔ rotate. Left trigger: build; left Grip: cancel."},
 {"Grafik / Ansicht","Graphics / View"},
 {"Spiel: immer Tabletop","Game: always tabletop"},
 {"Videos: Bildschirm","Videos: screen"},
 {"Stereo: Multiview","Stereo: Multiview"},
 {"GPU-Zeit: bei Multiview gesperrt","GPU time: disabled in multiview"},
 {"Darstellung noch nicht bereit","Presentation not ready"},
 {"Ladevorgang","Loading"},
 {"Kamerasequenz","Camera sequence"},
 {"Kein laufendes Spiel","No active match"},
 {"Normales Fenster gewählt","Normal window selected"},
 {"Spielmenü","Game menu"},
 {"Tabletop wird vorbereitet","Preparing tabletop"},
 {"Tabletop ausgeschaltet","Tabletop disabled"},
 {"Schatten A: Original","Shadows A: Original"},
 {"Schatten B: Leicht","Shadows B: Light"},
 {"Messung: AN","Timing: ON"},
 {"Messung: AUS","Timing: OFF"},
 {"Stereo: Kompakt","Stereo: Compact"},
 {"Stereo: Referenz","Stereo: Reference"},
 {"Zusatzwelt: Auto","Extra world: Auto"},
 {"Zusatzwelt: Immer","Extra world: Always"},
 {"Zusatzwelt aus","Extra world off"},
 {"Zusatzwelt aktiv","Extra world active"},
 {"Darstellung wird wiederhergestellt","Restoring display"},
 {"Die Spielwelt wird neu gezeichnet. Bitte die Trigger loslassen.","Redrawing the game world. Please release the triggers."},
 {"Schatten A/B nur diese Sitzung; B ohne Volumen","Session-only shadow A/B; B disables volumes"},
 {"Messung: Tabletop öffnen, kurz ruhig halten","Timing: enter tabletop, hold still briefly"},
 {"P12 · A/B: gleiche Szene, Auflösung und Kamera","P12 · A/B: same scene, resolution and camera"},
 {"GPU nicht verfügbar","GPU unavailable"},
 {"GPU wartet / verworfen","GPU pending / discarded"},
 {"Fertig","Done"},
 {"Befehle · P11.1","Commands · P11.1"},
 {"%s · %.2f m · Karte %.1fx · P11.1","%s · %.2f m · Map %.1fx · P11.1"},
 {"Gemischte Formationen: zuerst einzeln lösen","Mixed formations: release each formation first"},
 {"Befehle · P11","Commands · P11"},
 {"Taktik −","Tactics −"},
 {"Taktik +","Tactics +"},
 {"Formation lösen","Release formation"},
 {"Formation bilden","Create formation"},
 {"Zwangsbewegung","Force move"},
 {"Ohne Verfolgung","Guard: no pursuit"},
 {"Ansicht merken","Save view"},
 {"KARTENPLÄTZE · merken → A–D","MAP VIEWS · save → A–D"},
 {"Bewachen: Boden oder verbündetes Objekt anklicken","Guard: click ground or an allied object"},
 {"Ohne Verfolgung: Bodenposition anklicken","No pursuit: click ground position"},
 {"Zwangsbewegung: Bodenposition anklicken","Force move: click ground position"},
 {"Ungültiges Ziel: Boden oder anderes verbündetes Objekt","Invalid target: choose ground or another allied object"},
 {"Keine Bodenposition getroffen","No ground position hit"},
 {"Im Dialog oder bei gesperrter Kamera nicht verfügbar","Unavailable in a dialog or while camera is locked"},
 {"Zuerst eigene bewegliche Einheiten auswählen","First select your own mobile units"},
 {"Formation benötigt mindestens zwei Einheiten","Formation needs at least two units"},
 {"Kartenplatz leer: Ansicht merken → A–D","Empty map slot: Save view → A–D"},
 {"Kartenansicht gespeichert (nur diese Partie)","Map view saved (this match only)"},
 {"Kartenansicht aufgerufen; Tisch bleibt unverändert","Map view recalled; table unchanged"},
 {"Formation: aktuelle Anordnung zusammenhalten. Erneut klicken löst sie auf.","Formation: keep the current arrangement together. Click again to release it."},
 {"Zwangsbewegung: danach Boden anklicken. Ersetzt den Auftrag; keine Wegpunktfolge.","Force move: then click ground. Replaces the order; not a waypoint queue."},
 {"Ohne Verfolgung: danach Boden anklicken. Bewacht dort ohne Gegner zu verfolgen.","No pursuit: then click ground. Guards that area without pursuing enemies."},
 {"Ansicht merken: A–D wählen. Überschreibt diesen Kartenplatz, nur für diese Partie.","Save view: choose A–D. Replaces that map slot, for this match only."},
 {"A–D ruft die Kamera auf. Erst Ansicht merken → A–D zum Speichern. Tisch bleibt stehen.","A–D recalls the camera. Use Save view → A–D to store it first. Table stays put."},
 {"Bewachen: danach Boden oder anderes verbündetes Objekt anklicken. Bewegliche Ziele werden begleitet.","Guard: then click ground or another allied object. Mobile targets are escorted."},
 {"Zahl ruft die Gruppe auf. Zum Anlegen: Einheiten markieren → Speichern → Zahl.","Number recalls a group. To create: select units → Save selection → number."},
 {"Taktik aufklappen: Formation, Zwangsbewegung, Bewachen ohne Verfolgung und Kartenplätze.","Expand tactics: formation, force move, guard without pursuit, and map views."},
 {"Ansicht merken: jetzt A–D wählen","Save view: now choose A–D"},
 {"BEFEHLE","COMMANDS"},{"Befehle · P10.3","Commands · P10.3"},{"Arbeitsplatz","Workspace"},
 {"Fenster","Windows"},{"Einheiten","Units"},{"Gruppen","Groups"},{"Ansicht","View"},
 {"Auswahl / Befehle","Select / orders"},{"Kontextbefehl","Context order"},{"Einheit wählen","Select unit"},
 {"Auswahl +/-","Selection +/-"},{"Bereich: zwei Ecken","Box: two corners"},{"Bereich hinzufügen","Add selection box"},
 {"Bewegen","Move"},{"Angriffsmarsch","Attack move"},{"Zwangsangriff","Force attack"},
 {"Erzwungener Angriff","Force attack"},{"Position bewachen","Guard position"},{"STOPP","STOP"},
 {"Auseinanderlaufen","Scatter"},{"Freier Bauarbeiter","Idle worker"},{"Wegpunkte an / aus","Waypoints on / off"},
 {"Gleicher Typ: Karte","Same type: whole map"},{"Alle Einheiten","All units"},{"Held auswählen","Select hero"},
 {"Alle Flugzeuge","All aircraft"},{"Nächste Einheit","Next unit"},{"Nächster Bauarbeiter","Next worker"},
 {"Abbrechen / Abwahl","Cancel / deselect"},{"GRUPPEN · Zahl = auswählen","GROUPS · number = recall"},
 {"Speichern","Save selection"},{"Zur Auswahl","Add to selection"},{"Zentrieren","Center view"},
 {"Gruppe ersetzen","Replace group"},{"Neu / Erweitern","New / Extend"},
 {"Zahl wählt Gruppe; Aktion → Zahl führt sie aus","Number recalls group; action → number performs it"},
 {"Gruppe ersetzen: jetzt Zahl wählen","Replace group: choose a number now"},
 {"Neu / Erweitern: jetzt Zahl wählen","New / Extend: choose a number now"},
 {"Zentrieren: Zahl wählen","Center view: choose number"},
 {"Gruppe leer: Einheiten wählen → Speichern → Zahl","Empty group: select units → Save selection → number"},
 {"Keine Auswahl: zuerst eigene Einheiten markieren","No selection: first select your own units"},
 {"Speicherauftrag gesendet; Belegung siehe Gruppentaste","Save requested; see group button for membership"},
 {"Gruppe zur Auswahl hinzugefügt, nicht neu gespeichert","Group added to selection, not saved again"},
 {"Gruppe gespeichert","Group saved"},{"Auswahl zur Gruppe hinzugefügt","Selection added to group"},
 {"Gruppenansicht zentriert","View centered on group"},{"Gruppe ausgewählt","Group recalled"},
 {"Hilfe","Help"},{"Communicator","Communicator"},{"Zurück zu Befehlen","Back to commands"},{"Weiter","Next"},
 {"Tisch","Table"},{"Baufenster","Build window"},{"Bildschirm","Screen"},
 {"%s · %.2f m · Karte %.1fx · P11","%s · %.2f m · Map %.1fx · P11"},
 {"Tisch wählen","Select table"},{"Bildschirm wählen","Select screen"},{"Baufenster wählen","Select build window"},
 {"Kleiner","Smaller"},{"Größer","Larger"},{"Näher","Closer"},{"Weiter weg","Farther"},{"Höher","Higher"},{"Tiefer","Lower"},
 {"Flacher","Flatter"},{"Steiler","More upright"},{"Links drehen","Rotate left"},{"Rechts drehen","Rotate right"},
 {"Mehr Karte","More map"},{"Weniger Karte","Less map"},{"Greifen / Anordnen","Grab / arrange"},
 {"Position zurücksetzen","Reset position"},{"Tabletop an / aus","Tabletop on / off"},{"Schließen","Close"},
 {"Alles vor mir ausrichten","Align everything in front of me"},
 {"Spielfläche verlassen?","Leave the play surface?"},
 {"Die Tisch-/Bodenplatzierung wird verlassen.","This leaves the table/floor placement."},
 {"Brett und Fenster kommen gemeinsam vor dich.","The board and windows will move in front of you together."},
 {"Verlassen & vor mir ausrichten","Leave surface & align in front"},
 {"Gruppen verwalten","Manage groups"},{"Zurück zum Spiel","Back to game"},{"Gruppe vorher","Previous group"},
 {"Gruppe weiter","Next group"},{"Auswahl speichern","Save selection"},{"Gruppe auswählen","Recall group"},
 {"Gruppe zur Auswahl","Add group to selection"},{"Zur Gruppe schauen","Center on group"},
 {"Einheitenbefehle","Unit commands"},{"Fenster einstellen","Adjust windows"},
 {"Jetzt Tabletop","Use tabletop now"},{"Jetzt normale Ansicht","Use normal view now"},
 {"Als Startansicht","Use as start view"},{"Normalstart zurück","Restore normal start"},
 {"Lebenspunkte an/aus","Health bars on/off"},{"Einheitenringe an/aus","Unit rings on/off"},{"Brettkörper an/aus","Table body on/off"},
 {"Linkshändig: AN","Left-handed: ON"},{"Linkshändig: AUS","Left-handed: OFF"},{"Foto-Anordnung","Photo arrangement"},
 {"Auflösung: Hoch","Resolution: High"},{"Auflösung: Ausgewogen","Resolution: Balanced"},
 {"Ultra+","Ultra+"},
 {"Sprache: Deutsch","Language: German"},{"Sprache: English","Language: English"},
 {"Start: %s · LP %s · Ringe %s · Brett %s","Start: %s · HP %s · Rings %s · Table %s"},
 {"an","on"},{"aus","off"},{"Rahmen hinzufügen","Add selection box"},{"Auswahlrahmen","Selection box"},
 {"%s%s · %d gewählt · Gruppe %d%s","%s%s · %d selected · Group %d%s"},
 {" (loslassen zum Wählen)"," (release to select)"},{" (zweite Ecke)"," (second corner)"},{" · Wegpunkte AN"," · Waypoints ON"},
 {"Einheitensteuerung","Unit controls"},{"Zuerst eine eigene Einheit auswählen","First select your own unit"},
 {"Bewachen: Position auf dem Tisch anklicken","Guard: click a position on the table"},
 {"Bewegen: Ziel auf dem Tisch anklicken","Move: click destination on the table"},
 {"Angriffsmarsch: Zielposition anklicken","Attack move: click destination"},
 {"Zwangsangriff: Ziel auf dem Tisch anklicken","Force attack: click target on the table"},
 {"Bereich: zwei Ecken auf dem Tisch anklicken","Box: click two corners on the table"},
 {"Einheit auf dem Tisch anklicken","Click a unit on the table"},
 {"XR sofort; Spieltexte nach Neustart (Sprachdateien nötig)","XR immediately; game text after restart (language files required)"},
 {"Spieltexte vorbereitet: Neustart nötig","Game text prepared: restart required"},
 {"Nur XR übersetzt: Spiel-Sprachdateien fehlen","XR translated only: game language files missing"},
 {"XR übersetzt; Spielsprache konnte nicht gespeichert werden","XR translated; could not save game language"},
 {"Rechts: Trigger / Rahmen · Links: Stick = Karte","Right: trigger / drag box · Left: stick = pan"},
 {"Linker Grip: Auswahl +/- · A: Befehle ein/aus","Left grip: selection +/- · A: toggle commands"},
 {"Links: Trigger / Rahmen · Rechts: Stick = Karte","Left: trigger / drag box · Right: stick = pan"},
 {"Rechter Grip: Auswahl +/- · X: Befehle ein/aus","Right grip: selection +/- · X: toggle commands"},
 // GeneralsX @feature Ultron 15/09/2026 P21 section headers, chip values and
 // state strings for the redesigned UI/Commands panels.
 {"Befehle","Commands"},
 {"Auftrag · danach Ziel wählen","Order · then choose target on the table"},
 {"Sofort & Auswahl","Instant & selection"},
 {"Gruppen · Zahl wählt · Speichern → Zahl legt an","Groups · number recalls · Save → number creates"},
 {"Gruppen · Aktion wählen → Zahl","Groups · choose action → number"},
 {"Wegpunkte aktiv: Ziele nacheinander anklicken; erneut Wegpunkte tippen beendet","Waypoints active: click destinations in order; tap Waypoints again to finish"},
 {"Taktik · erweitert","Tactics · advanced"},
 {"Ziel","Target"},
 {"Größe & Abstand","Size & distance"},
 {"Lage","Placement"},
 {"Karte","Map"},
 {"Aktionen","Actions"},
 {"Darstellung","Presentation"},
 {"Grafik","Graphics"},
 {"Steuerung & Sprache","Controls & language"},
 {"Auswahl","Selection"},
 {"Sofort","Instant"},
 {"Navigation","Navigation"},
 {"Direkter im Spiel: Befehle-Konsole (%s)","Faster in game: commands console (%s)"},
 {"Bearbeitung: %s · %.2f m · Karte %.1fx","Editing: %s · %.2f m · Map %.1fx"},
 {"AN","ON"},
 {"AUS","OFF"},
 {"Wegpunkte","Waypoints"},
 {"Lebenspunkte","Health bars"},
 {"Einheitenringe","Unit rings"},
 {"Brettkörper","Board frame"},
 {"Auflösung","Resolution"},
 {"Hoch","High"},
 {"Ausgewogen","Balanced"},
 {"Schatten","Shadows"},
 {"Original","Original"},
 {"Leicht","Light"},
 {"Messung","Measurement"},
 {"Stereo","Stereo"},
 {"Multiview","Multiview"},
 {"Kompakt","Compact"},
 {"Referenz","Reference"},
 {"Zusatzwelt","Extra world"},
 {"Auto","Auto"},
 {"Immer","Always"},
 {"Sprache","Language"},
 {"Deutsch","German"},
 {"English","English"},
 {"Linkshändig","Left-handed"},
 // GeneralsX @feature Muse 16/09/2026 Match-result card titles and hint.
 {"Sieg!","Victory!"},
 {"Niederlage","Defeat"},
 {"Partie beendet","Match over"},
 {"Die Partie ist entschieden.\nBeliebige Taste zum Schließen.","The match is decided.\nPress any button to dismiss."}
};
inline const char *xrTr(const char *source) {
 if(g_xrLanguage==XrLanguage::German)return source;
 for(const auto &entry:kXrTranslations)if(!std::strcmp(source,entry.de))return entry.en;
 return source; // Original game labels are never guessed or machine-replaced.
}
inline std::string xrLines(const std::string &source) {
 std::string result;size_t start=0;
 do {const auto end=source.find('\n',start);result+=xrTr(source.substr(start,end-start).c_str());
  if(end==std::string::npos)break;result+='\n';start=end+1;
 }while(start<=source.size());return result;
}
// Help stays in the same directly reachable console; no settings submenu.
inline const char *xrCommandHelp(int page) {
 static const XrTranslation pages[]={
 {"GRUPPEN ANLEGEN ODER ERSETZEN\n1. Eigene Einheiten markieren (Trigger oder Rahmen).\n2. Gruppe ersetzen antippen.\n3. Gruppennummer wählen.\n\nZahl allein: gespeicherte Gruppe auswählen. Die kleine Zahl zeigt lebende Mitglieder.\n\nNEU / ERWEITERN\n1. Nur die neuen oder zusätzlichen Einheiten markieren.\n2. Neu / Erweitern antippen.\n3. Gruppennummer wählen. Eine leere Nummer legt eine Gruppe an; eine belegte erweitert sie. Kein weiteres Speichern nötig.\n\nZentrieren → Zahl bewegt nur die Kamera. Gruppen sind Schnellauswahlen, keine festen Formationen.",
  "CREATE OR REPLACE A GROUP\n1. Select your units (trigger or drag box).\n2. Tap Replace group.\n3. Choose a group number.\n\nNumber alone: recall the saved group. The small number shows living members.\n\nNEW / EXTEND\n1. Select only the new or additional units.\n2. Tap New / Extend.\n3. Choose a number. An empty slot creates a group; an occupied one extends it. No second save is needed.\n\nCenter view → number only moves the camera. Groups are selection shortcuts, not fixed formations."},
 {"EINHEITEN BEFEHLIGEN\nAuswählen → Bewegen / Angriffsmarsch / Zwangsangriff / Position bewachen → Ziel auf dem Tisch anklicken.\n\nBewachen: Boden oder verbündetes Objekt anklicken. STOPP und Auseinanderlaufen wirken sofort.\n\nAuswahl / Befehle: normaler Kontextmodus. Feind anklicken = angreifen; Gelände = bewegen. Eigene Objekte können Einsteigen oder Reparieren bedeuten.\n\nWegpunkte: Einheiten auswählen → Wegpunkte einschalten → Ziele in gewünschter Reihenfolge anklicken → Wegpunkte wieder ausschalten. Die Route bleibt währenddessen auf der Karte sichtbar. Abbrechen oder STOPP beendet den Modus.\n\nBauen, Spezialfähigkeiten, Upgrades und Produktionsaufträge bleiben im originalen Baufenster.",
  "ISSUE UNIT ORDERS\nSelect → Move / Attack move / Force attack / Guard position → click target on the table.\n\nGuard: click ground or an allied object. STOP and Scatter act immediately.\n\nSelect / orders: normal context mode. Click enemy = attack; terrain = move. Friendly objects may mean enter or repair.\n\nWaypoints: select units → enable Waypoints → click destinations in the desired order → disable Waypoints. The route stays visible on the map while plotting. Cancel or STOP ends the mode.\n\nConstruction, special abilities, upgrades and production orders stay in the original build window."},
 {"AUSWAHL UND STEUERUNG\nTrigger kurz: auswählen / Kontextbefehl. Halten und ziehen: Auswahlrahmen. Grip der anderen Hand beim Drücken: zur Auswahl hinzufügen / entfernen.\n\nStick der anderen Hand: Karte verschieben. Stick der Zeigehand: drehen / zoomen.\n\nGleicher Typ: alle passenden Einheiten auf der Karte. Alle Einheiten schließt Gebäude aus. Freier Bauarbeiter sucht einen untätigen Arbeiter.\n\nCommunicator öffnet das Originalfenster: im Einzelspieler Briefing, im Mehrspieler Spieler/Chat. Tabletop unterstützt derzeit Offline-Partien.\n\nUI → Ansicht: Sprache und Linkshändigkeit.",
  "SELECTION AND CONTROLS\nShort trigger press: select / context order. Hold and drag: selection box. Hold the other hand's grip at press: add / remove selection.\n\nOther hand's stick: pan map. Pointing hand's stick: rotate / zoom.\n\nSame type: all matching units on the map. All units excludes buildings. Idle worker finds an available worker.\n\nCommunicator opens the original window: briefing in single player, players/chat in multiplayer. Tabletop currently supports offline matches.\n\nUI → View: language and handedness."}
 ,{"TAKTIK DIREKT AUFKLAPPEN\nFormation bilden: mindestens zwei Einheiten markieren. Ihre aktuelle Anordnung wird zusammengehalten. Formation lösen hebt das wieder auf. Gruppen speichern nur die Auswahl.\n\nZwangsbewegung → Boden anklicken: ersetzt den Auftrag, ohne Wegpunktfolge.\n\nBewachen → Boden oder anderes verbündetes Objekt anklicken. Bewegliche Ziele werden begleitet.\n\nOhne Verfolgung → Boden anklicken: Bereich bewachen, ohne Gegner zu verfolgen.\n\nKARTENPLÄTZE\nAnsicht merken → A–D speichert. A–D allein ruft auf. Gilt nur für diese Partie; Tisch und Fenster bleiben stehen.\n\nAbbrechen beendet die Zielwahl. Bei Trackingverlust wird kein Auftrag ausgeführt.",
 "EXPAND TACTICS DIRECTLY\nCreate formation: select at least two units. Keeps their current arrangement together. Release formation undoes this. Groups only save a selection.\n\nForce move → click ground: replaces the order, without a waypoint queue.\n\nGuard → click ground or another allied object. Mobile targets are escorted.\n\nNo pursuit → click ground: guard the area without pursuing enemies.\n\nMAP VIEWS\nSave view → A–D stores a view. A–D alone recalls it. This match only; table and windows stay put.\n\nCancel ends targeting. Tracking loss never issues an order."}
 };const auto &entry=pages[page>=0 && page<4 ? page:0];
 return g_xrLanguage==XrLanguage::English ? entry.en:entry.de;
}
